### ISSUE TITLE
Training multi-layer model does not work?

### ISSUE THREAD

**Issue by yupenghe** [wenjiegroup/PEDLA#1]
Hi,
I tried to run `A1_training_of_PEDLA_for_H1.m` with `sizes = [500 500]`. However, I found that the training was not done successfully. The accuracy is much worse than any single layer model (e.g. `size = [10]`). Example results:
## size = [10]

training accuracy of DNN:98.0191%
training accuracy of PEDLA:93.9567%
## size = [500 500]

training accuracy of DNN:97.9703%
training accuracy of PEDLA:49.709%

Do you have any idea about this? Thanks!

Yupeng

**Comment by wenjiegroup** [comment]
If you used the training data we provided, then a model with two hidden layers of size [500 500] will be better than single layer (see Table S3). However, every time PEDLA is run with a different random seed, the random seed you run with maybe happens to cause such a result. If so, running PEDLA again will get a new result.  If PEDLA was trained with your own training data, the optimal model for your data is unknown. It is possible that single layer is more suitable for your data. In addition, make sure that the number of epoch is 50 or larger than 50. 
If you still have any problem, welcome to contact us.

All the best,

Wenjie Shu, Ph.D
Department of Biotechnology
Beijing Institute of Radiation Medicine
Beijing, China

From: Yupeng He
Date: 2016-07-14 13:45
To: wenjiegroup/PEDLA
Subject: [wenjiegroup/PEDLA] Training multi-layer model does not work? (#1)
Hi,
I tried to run A1_training_of_PEDLA_for_H1.m with sizes = [500 500]. However, I found that the training was not done successfully. The accuracy is much worse than any single layer model (e.g. size = [10]). Example results:
size = [10]
training accuracy of DNN:98.0191%
training accuracy of PEDLA:93.9567%
size = [500 500]
training accuracy of DNN:97.9703%
training accuracy of PEDLA:49.709%
Do you have any idea about this? Thanks!
Yupeng

**Comment by yupenghe** [comment]
Thank you. I have some other questions which are related to the results in your paper. Would you recommend me to post here (or on a new issue) or to email the corresponding author?
